#!/usr/bin/env sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"


# LAUNCHERS
killall cleanfullscreen
cleanfullscreen &
#wal -i "$HOME/.local/bin/wallpapers/Future"
#source "$HOME/.cache/wal/colors.sh"


# Bspwm configs
bspc config border_width         3
bspc config window_gap           0
bspc config top_padding          26
bspc config bottom_padding       0
bspc config right_padding        0
bspc config left_padding         0
bspc config split_ratio          0.50


bspc config borderless_monocle    false  # no borders in monocle layout.
bspc config gapless_monocle       false  # no gaps in monocle layout.
bspc config single_monocle        true  # use monocle layout if there is only 1 window.
bspc config automatic_scheme alternate
bspc config center_pseudo_tiled   true
bspc config initial_polarity second_child
bspc config focus_follows_pointer false
#bspc config external_rules_command $HOME/.config/bspwm/spotify_rules
#b#spc config external_rules_command $HOME/.local/bin/float.sh
#bspc config external_rules_command $HOME/.config/bspwm/external_rules.sh
#bspc config remove_disabled_monitors true
#bspc config merge_overlapping_monitors true


# Moving foating windows
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


# Border colors
bspc config normal_border_color $(awk '$1 ~ "$color0" { print $2 }' ~/.Xresources)
bspc config active_border_color $(awk '$1 ~ "green" { print $2 }' ~/.Xresources)
bspc config focused_border_color $(awk '$1 ~ "green" { print $2 }' ~/.Xresources)
#bspc config presel_feedback_color $(awk '$1 ~ "red" { print $2 }' ~/.Xresources)
#bspc config urgent_border_color $(awk '$1 ~ "$color8" { print $2 }' ~/.Xresources)


# Single monitor
#bspc monitor -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor  -d "☢️ " "🤬 " "⚒️ " "🍭 " "🎲 " "🎬 " "🔰 "  "🎯 " "📀 "
#bspc monitor -d "Web " "Chat " "Edit " "Music " "Tor " "Video " "Vbox " "File " "Float "
bspc monitor -d " "  " "  " "  " "  " "  " "  " "  " "  " "  " "
#bspc monitor -d "I" "II" "III" "IV" "V" "VI" "VII" "VIII" "IX" "X"


# Dual monitor
#bspc monitor LVDS1 -d 1 2 3 4
#bspc monitor DP3 -d  5 6 7 8 9


# Open applications on specific workspaces
bspc rule -a Brave-browser desktop='^1'
bspc rule -a discord desktop='^2' follow=on
bspc rule -a TelegramDesktop desktop='^2' follow=on
bspc rule -a Subl3 desktop='^3' follow=on
bspc rule -a Steam desktop='^4' state=fullscreen follow=on
bspc rule -a Vlc desktop='^7' state=fullscreen follow=on
bspc rule -a Pcmanfm desktop='^8' follow=on
bspc rule -a Spotify desktop='^9' follow=on
bspc rule -a VirtualBox Manager state=fullscreen
bspc rule -a VirtualBox Machine state=fullscreen
#bspc rule -a Ulauncher  border=off
#bspc rule -a burp-StartBurp desktop='^9' state=floating follow=on


# Floating apps
#bspc rule -a feh state=floating
bspc rule -a qView state=floating
bspc rule -a Pulseaudio-equalizer-gtk  state=floating
bspc rule -a Gpick state=floating
bspc rule -a Lxappearance state=floating center=true rectangle=870x550+500+270
bspc rule -a Pavucontrol state=floating center=true rectangle=870x550+500+270
bspc rule -a Pcmanfm:Dialog state=floating
bspc rule -a Alacritty:newsboat state=floating center=true
bspc rule -a URxvt state=floating
bspc rule -a $TERMFLOAT:calcurse state=floating rectangle=70x20-620+30
bspc rule -a Sxiv state=floating center=true
bspc rule -a mpv state=floating

# Manage apps
bspc rule -a polybar manage=off
bspc rule -a Screenkey manage=off


###########END####################################################################
